- name: Make sure configs directory exists
  become: true
  file:
    path: /root/truenas/configs
    state: directory

- name: Add .resticrc file
  become: true
  vars:
    resticrc: |
      export AWS_ACCESS_KEY_ID={{ aws.access_key_id }}
      export AWS_SECRET_ACCESS_KEY={{ aws.secret_access_key }}
      export RESTIC_REPOSITORY=s3:s3.amazonaws.com/{{ aws.backup_s3_bucket }}/restic
      export RESTIC_PASSWORD={{ restic.password }}
  copy:
    content: "{{ resticrc }}"
    dest: /root/truenas/configs/.resticrc
    mode: "0777"